lint:
  tags:
    - shared
  image: "quay.io/fedora/fedora:35"
  before_script:
    - dnf install -y pre-commit make git-core
  script:
    - pre-commit run --from-ref origin/master --to-ref HEAD

test:
  tags:
    - covscan-ci-runner
  before_script:
    - rm -rf kobo
    - git clone --depth 1 https://github.com/release-engineering/kobo.git
    - podman pull registry-proxy.engineering.redhat.com/rh-osbs/rhel8-postgresql-12
    - podman build -f containers/Dockerfile.hub -t osh-hub .
    - podman build -f containers/Dockerfile.worker -t covscanworker .
    - podman-compose up --no-start
    - podman start db osh-hub
  script:
    - podman exec -it osh-hub python3 covscanhub/manage.py test || exit 1
  after_script:
    - podman-compose logs db
    - podman-compose logs osh-hub
    - podman-compose down

gitlab-ci-build-on-copr:
  tags:
    - shared
  image: "quay.io/fedora/fedora:35"
  before_script:
    - mkdir -p ~/.config
    - echo "[copr-cli]" > ~/.config/rhcopr
    - echo "$COPR_CLI_USERNAME" | base64 --decode >> ~/.config/rhcopr
    - echo "$COPR_CLI_TOKEN" | base64 --decode >> ~/.config/rhcopr
    - echo "$COPR_CLI_LOGIN" | base64 --decode >> ~/.config/rhcopr
    - echo "$COPR_CLI_COPR_URL" | base64 --decode >> ~/.config/rhcopr
    - dnf install -y findutils git make python python3-dnf-plugins-core python3-setuptools rpm-build
    - dnf copr enable copr.devel.redhat.com/rhcopr-project/toolset -y
    - dnf install -y rhcopr
  script:
    - make srpm
    - rhcopr build gitlab-ci-build-on-copr *.src.rpm
