lint:
  tags:
    - shared
  image: "quay.io/fedora/fedora:35"
  before_script:
    - dnf install -y pre-commit make git-core
  script:
    - pre-commit run --from-ref origin/master --to-ref HEAD

test:
  tags:
    - covscan-ci-runner
  before_script:
    - rm -rf kobo
    - git clone --depth 1 https://github.com/release-engineering/kobo.git
    - podman pull registry-proxy.engineering.redhat.com/rh-osbs/rhel8-postgresql-12
    - podman build -f containers/Dockerfile.hub -t osh-hub .
    - podman build -f containers/Dockerfile.worker -t covscanworker .
    - podman-compose up --no-start
    - podman start db osh-hub
  script:
    - podman exec -it osh-hub python3 covscanhub/manage.py test || exit 1
  after_script:
    - podman-compose logs db
    - podman-compose logs osh-hub
    - podman-compose down

gitlab-ci-build-on-copr:
  tags:
    - shared
  image: "registry.access.redhat.com/ubi8"
  before_script:
    - mkdir -p ~/.config
    - echo "[copr-cli]" > ~/.config/rhcopr
    - echo -n "username = " >> ~/.config/rhcopr
    - echo "$COPR_CLI_USERNAME" | base64 --decode >> ~/.config/rhcopr
    - echo -n "token = " >> ~/.config/rhcopr
    - echo "$COPR_CLI_TOKEN" | base64 --decode >> ~/.config/rhcopr
    - echo -n "login = " >> ~/.config/rhcopr
    - echo "$COPR_CLI_LOGIN" | base64 --decode >> ~/.config/rhcopr
    - echo -n "copr_url = " >> ~/.config/rhcopr
    - echo "$COPR_CLI_COPR_URL" | base64 --decode >> ~/.config/rhcopr
    - dnf install -y findutils git make python36 python3-dnf-plugins-core python3-setuptools rpm-build
    - dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    - cp containers/rhel-8-pulp.repo containers/rcm-tools-for-rhel-8.repo /etc/yum.repos.d/
    - dnf copr enable @copr/copr -y
    - dnf copr enable copr.devel.redhat.com/rhcopr-project/toolset -y
    - dnf install -y rhcopr
  script:
    - make srpm
    - rhcopr build gitlab-ci-build-on-copr *.src.rpm | tee rhcopr-build.log
    - copr_url=$(grep "https://copr.*coprs/build/" rhcopr-build.log)
    - build_id=$(basename $copr_url)
    - rhcopr download-build $build_id -r epel-8-x86_64
    - dnf install -y $(ls epel-8-x86_64/*.rpm | grep -v "prod\|stage\|src")
