version: '3'

services:
  db:
    image: registry-proxy.engineering.redhat.com/rh-osbs/rhel8-postgresql-12
    container_name: db
    hostname: db
    environment:
      POSTGRESQL_PASSWORD: velryba
      POSTGRESQL_USER: covscanhub
      POSTGRESQL_DATABASE: covscanhub
    ports:
      - "5432:5432"
    networks:
      - internal-network

  osh-hub:
    image: osh-hub
    container_name: osh-hub
    hostname: osh-hub
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - internal-network
    volumes:
      - ./:/src:z
    stdin_open: true
    tty: true

  osh-worker:
    image: osh-worker
    container_name: osh-worker
    hostname: osh-worker
    depends_on:
      - osh-hub
    networks:
      - internal-network
    volumes:
      - ./:/src:z
    privileged: true
    stdin_open: true
    tty: true

  osh-client:
    image: osh-client
    container_name: osh-client
    hostname: osh-client
    depends_on:
      - osh-hub
    networks:
      - internal-network
    volumes:
      - ./:/src:z
    stdin_open: true
    tty: true
    profiles:
      - full-dev

networks:
  internal-network:
